//! Track only closing ranges generated by this TIP, using native TSF anchors.
use crate::{
    edit,
    tip::{lock, TipState},
};
use retype_types::symbols::{eligible, rules};
use std::{mem::ManuallyDrop, sync::Arc};
use windows::Win32::{Foundation::E_FAIL, UI::TextServices::*};
use windows_core::{Interface, Result};

pub(crate) struct OwnedPair {
    context: ITfContext,
    range: ITfRange,
    left: char,
    right: char,
}
fn selection(ctx: &ITfContext, ec: u32) -> Result<ITfRange> {
    // SAFETY: Called only in the context's granted edit session.
    unsafe {
        let mut selected = [TF_SELECTION::default()];
        let mut count = 0;
        let result = ctx.GetSelection(ec, TF_DEFAULT_SELECTION, &mut selected, &mut count);
        let range = ManuallyDrop::take(&mut selected[0].range);
        result?;
        range.filter(|_| count == 1).ok_or_else(|| E_FAIL.into())
    }
}
fn text(range: &ITfRange, ec: u32) -> Result<String> {
    let mut buf = [0; 3];
    let mut count = 0;
    // SAFETY: Read at most three UTF-16 units with a valid edit cookie.
    unsafe {
        range.GetText(ec, 0, &mut buf, &mut count)?;
    }
    let Some(value) = buf.get(..count as usize) else {
        return Err(E_FAIL.into());
    };
    Ok(String::from_utf16_lossy(value))
}
fn nearby(caret: &ITfRange, ec: u32, before: bool) -> Result<Option<char>> {
    // SAFETY: Only shift a clone in this context, by one UTF-16 unit.
    unsafe {
        let range = caret.Clone()?;
        let mut moved = 0;
        if before {
            range.ShiftStart(ec, -1, &mut moved, std::ptr::null())?;
        } else {
            range.ShiftEnd(ec, 1, &mut moved, std::ptr::null())?;
        }
        Ok(text(&range, ec)?.chars().next())
    }
}
fn set_caret(ctx: &ITfContext, ec: u32, range: &ITfRange, anchor: TfAnchor) -> Result<()> {
    // SAFETY: Native selection and range belong to the granted context.
    unsafe {
        let caret = range.Clone()?;
        caret.Collapse(ec, anchor)?;
        let mut selection = TF_SELECTION {
            range: ManuallyDrop::new(Some(caret)),
            style: TF_SELECTIONSTYLE {
                ase: TF_AE_NONE,
                fInterimChar: false.into(),
            },
        };
        let result = ctx.SetSelection(ec, std::slice::from_ref(&selection));
        ManuallyDrop::drop(&mut selection.range);
        result
    }
}
fn owned_at(
    state: &TipState,
    ctx: &ITfContext,
    ec: u32,
    caret: &ITfRange,
    close: Option<char>,
) -> Option<usize> {
    let mut pairs = lock(&state.symbol_pairs);
    pairs.retain(|p| {
        p.context == *ctx && text(&p.range, ec).ok().as_deref() == Some(&p.right.to_string())
    });
    pairs.iter().rposition(|p| {
        // SAFETY: Both native ranges belong to this context and cookie.
        (close.is_none() || close == Some(p.right))
            && unsafe {
                caret.IsEmpty(ec).is_ok_and(|v| v.as_bool())
                    && caret
                        .IsEqualStart(ec, &p.range, TF_ANCHOR_START)
                        .is_ok_and(|v| v.as_bool())
            }
    })
}
pub(crate) fn commit(
    state: &Arc<TipState>,
    ctx: &ITfContext,
    ec: u32,
    value: &str,
    key: Option<char>,
    chinese: bool,
    enabled: bool,
) -> Result<()> {
    let Some(key) = key.filter(|_| enabled) else {
        return edit::replace(state, ctx, ec, value, false);
    };
    let rule = rules(key, chinese);
    let Some(last) = value.chars().last() else {
        return edit::replace(state, ctx, ec, value, false);
    };
    // Some kernel commits contain only the preceding word, not the typed symbol.
    if last != key
        && !rule.opening.is_some_and(|(a, b)| last == a || last == b)
        && rule.closing != Some(last)
    {
        return edit::replace(state, ctx, ec, value, false);
    }
    let prefix = &value[..value.len() - last.len_utf8()];
    let initial = selection(ctx, ec).ok();
    // SAFETY: Only query the selected range in its edit session.
    let collapsed = initial
        .as_ref()
        .is_some_and(|r| unsafe { r.IsEmpty(ec).is_ok_and(|v| v.as_bool()) });
    if !collapsed && lock(&state.composition).is_none() {
        return edit::replace(state, ctx, ec, value, false);
    }
    // Finish the word before testing adjacency: the closer's native range follows the edit.
    if !prefix.is_empty() {
        edit::replace(state, ctx, ec, prefix, false)?;
    } else if lock(&state.composition).is_some() {
        edit::replace(state, ctx, ec, "", false)?;
    }
    let caret = selection(ctx, ec).ok();
    if let (Some(close), Some(caret)) = (rule.closing, caret.as_ref()) {
        if let Some(index) = owned_at(state, ctx, ec, caret, Some(close)) {
            let pair = lock(&state.symbol_pairs).remove(index);
            if crate::symbol_cursor::needs_forwarding(ctx) {
                // Chromium ignores selection-only TSF edits from an IME.
                // Keep the native caret before the closer and forward one Right.
                if crate::symbol_cursor::forward(state, ctx, crate::symbol_cursor::Direction::Right)
                    .is_ok()
                {
                    return Ok(());
                }
                lock(&state.symbol_pairs).push(pair);
                return Ok(());
            }
            if set_caret(ctx, ec, &pair.range, TF_ANCHOR_END).is_ok() {
                return Ok(());
            }
            return edit::replace(state, ctx, ec, &close.to_string(), false);
        }
    }
    let Some((left, right)) = rule.opening else {
        return edit::replace(
            state,
            ctx,
            ec,
            &rule.closing.unwrap_or(last).to_string(),
            false,
        );
    };
    let adjacent = caret
        .as_ref()
        .and_then(|c| Some((nearby(c, ec, true).ok()?, nearby(c, ec, false).ok()?)));
    edit::replace(state, ctx, ec, &left.to_string(), false)?;
    let Some((before, after)) = adjacent else {
        return Ok(());
    };
    if !eligible(left, right, before, after) {
        return Ok(());
    }
    // An editor may insert its own closer in response to the opener write.
    let Ok(current) = selection(ctx, ec) else {
        return Ok(());
    };
    // SAFETY: Recheck the app's selection after the opener has been inserted.
    if !unsafe { current.IsEmpty(ec).is_ok_and(|value| value.as_bool()) } {
        return Ok(());
    }
    let (Ok(current_before), Ok(current_after)) =
        (nearby(&current, ec, true), nearby(&current, ec, false))
    else {
        return Ok(());
    };
    if current_before != Some(left) || current_after == Some(right) {
        return Ok(());
    }
    // SAFETY: Insert under the same TSF write lock. Chromium moves the actual
    // caret to the end on commit regardless of a successful collapsed selection.
    unsafe {
        let insert: ITfInsertAtSelection = match ctx.cast() {
            Ok(i) => i,
            Err(_) => return Ok(()),
        };
        let range = match insert.InsertTextAtSelection(ec, TF_IAS_QUERYONLY, &[]) {
            Ok(r) => r,
            Err(_) => return Ok(()),
        };
        if range.SetText(ec, 0, &[right as u16]).is_err() {
            return Ok(());
        }
        // Exclude future inserts on either side of the closing character.
        let forwarding = crate::symbol_cursor::needs_forwarding(ctx);
        if range
            .SetGravity(ec, TF_GRAVITY_FORWARD, TF_GRAVITY_BACKWARD)
            .is_err()
            || set_caret(
                ctx,
                ec,
                &range,
                if forwarding {
                    TF_ANCHOR_END
                } else {
                    TF_ANCHOR_START
                },
            )
            .is_err()
            || (forwarding
                && crate::symbol_cursor::forward(state, ctx, crate::symbol_cursor::Direction::Left)
                    .is_err())
        {
            let _ = range.SetText(ec, 0, &[]);
            let _ = set_caret(ctx, ec, &range, TF_ANCHOR_START);
            return Ok(());
        }
        let mut pairs = lock(&state.symbol_pairs);
        if pairs.len() == 32 {
            pairs.remove(0);
        }
        pairs.push(OwnedPair {
            context: ctx.clone(),
            range,
            left,
            right,
        });
    }
    Ok(())
}
pub(crate) fn backspace(state: &Arc<TipState>, ctx: &ITfContext, ec: u32) -> Result<bool> {
    let caret = selection(ctx, ec)?;
    let Some(index) = owned_at(state, ctx, ec, &caret, None) else {
        return Ok(false);
    };
    let pairs = lock(&state.symbol_pairs);
    let pair = &pairs[index];
    // SAFETY: Expand only a verified closer and validate both characters before editing.
    unsafe {
        let range = pair.range.Clone()?;
        let mut moved = 0;
        range.ShiftStart(ec, -1, &mut moved, std::ptr::null())?;
        if text(&range, ec)? != format!("{}{}", pair.left, pair.right) {
            return Ok(false);
        }
        range.SetText(ec, 0, &[])?;
        // The pair is already deleted. Never pass Backspace on to the app again.
        let _ = set_caret(ctx, ec, &range, TF_ANCHOR_START);
    }
    drop(pairs);
    lock(&state.symbol_pairs).remove(index);
    Ok(true)
}
